site_name: Django ML Ops
site_url: https://eddyojb88.github.io/django_flow_forge/
docs_dir: 'docs'
site_dir: 'site'
theme:
  name: 'material'
nav:
  - Home: 'index.md'
  - 'installation.md'
  - Features:
    - 'flows_dashboard.md'
    - 'data_science_experiments.md'
  - Considerations:
    - 'considerations.md'
    - 'debugging.md'
    - 'strategies.md'
    - 'authorization.md'
    - 'roadmap.md'