# Generated by Django 5.0.2 on 2024-02-16 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mlops', '0002_processtask_task_output'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='processtask',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='processtask',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='django_mlops.process'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='processtask',
            unique_together={('process', 'task_name')},
        ),
        migrations.RemoveField(
            model_name='processtask',
            name='process_name',
        ),
    ]
