# Generated by Django 5.0.2 on 2024-02-17 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0004_processtask_nested_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processtask',
            old_name='nested_task',
            new_name='bidirectional_task',
        ),
    ]
