# Generated by Django 5.0.2 on 2024-02-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0006_remove_processtask_bidirectional_task_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processtask',
            old_name='bidirectional_dependencies',
            new_name='depends_bidirectionally_with',
        ),
    ]
