# Generated by Django 5.0.2 on 2024-02-17 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0007_rename_bidirectional_dependencies_processtask_depends_bidirectionally_with'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processtask',
            old_name='dependencies',
            new_name='depends_on',
        ),
    ]
