# Generated by Django 5.0.2 on 2024-02-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0009_processrun_taskrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtask',
            name='nested',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
