# Generated by Django 5.0.2 on 2024-02-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0010_processtask_nested'),
    ]

    operations = [
        migrations.AddField(
            model_name='processrun',
            name='process_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='task_complete',
            field=models.BooleanField(default=False),
        ),
    ]
