# Generated by Django 5.0.2 on 2024-02-19 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0011_processrun_process_complete_taskrun_task_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='process_display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processrun',
            name='executed_tasks',
            field=models.ManyToManyField(blank=True, related_name='executed_tasks', to='django_flow_forge.processtask'),
        ),
        migrations.AlterField(
            model_name='processrun',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_runs', to='django_flow_forge.process'),
        ),
    ]
