# Generated by Django 5.0.2 on 2024-02-19 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0013_remove_taskrun_task_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='task_snapshot_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='django_flow_forge.processtask'),
        ),
    ]
