# Generated by Django 5.0.2 on 2024-02-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0014_taskrun_task_snapshot_id_alter_taskrun_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrun',
            name='output',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
