# Generated by Django 5.0.2 on 2024-02-19 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0015_alter_taskrun_output'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcessRun',
            new_name='ExecutedProcess',
        ),
        migrations.RenameModel(
            old_name='TaskRun',
            new_name='ExecutedTask',
        ),
    ]
