# Generated by Django 5.0.2 on 2024-02-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0016_rename_processrun_executedprocess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executedtask',
            name='task_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='executedtask',
            name='task_snapshot_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
