# Generated by Django 5.0.2 on 2024-02-19 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0017_executedtask_task_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='in_current_code_base',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='executedprocess',
            name='process',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_runs', to='django_flow_forge.process'),
        ),
    ]
