# Generated by Django 5.0.2 on 2024-02-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0018_process_in_current_code_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executedprocess',
            name='process_id_snapshot',
            field=models.BigIntegerField(blank=True, default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executedprocess',
            name='process_name_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
