# Generated by Django 5.0.2 on 2024-02-25 13:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0024_alter_mlresult_executed_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='executedprocess',
            name='last_checkpoint_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
