# Generated by Django 5.0.2 on 2024-02-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0025_executedprocess_last_checkpoint_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='executedprocess',
            name='exceptions',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='processtask',
            name='depends_bidirectionally_with',
            field=models.ManyToManyField(blank=True, to='django_flow_forge.processtask'),
        ),
    ]
