# Generated by Django 5.0.2 on 2024-02-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0026_executedprocess_exceptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executedtask',
            name='task_status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
