# Generated by Django 5.0.2 on 2024-02-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0029_executedtask_exceptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executedprocess',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='executedtask',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
