# Generated by Django 5.0.2 on 2024-03-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executedflow',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('pending', 'Pending'), ('failed', 'Failed'), ('in_progress', 'In Progress')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='executedtask',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('pending', 'Pending'), ('failed', 'Failed'), ('in_progress', 'In Progress')], default='pending', max_length=20),
        ),
    ]
