# Generated by Django 5.0.2 on 2024-03-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0002_alter_executedflow_status_alter_executedtask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executedtask',
            name='exceptions',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
