# Generated by Django 5.0.2 on 2024-03-04 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0003_alter_executedtask_exceptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executedflow',
            name='exceptions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='executedtask',
            name='exceptions',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
