# Generated by Django 5.0 on 2024-03-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0004_alter_executedflow_exceptions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flow',
            options={'permissions': [('django_flow_admin_access', 'Can access Django Flow Admin')]},
        ),
    ]
