# Generated by Django 5.0 on 2024-04-14 08:05

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0008_executedflow_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.IntegerField(default=0)),
                ('total_batches', models.IntegerField(default=0)),
                ('executed_flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flow_batch', to='django_flow_forge.executedflow')),
            ],
        ),
        migrations.CreateModel(
            name='FlowBatchTempData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_index', models.IntegerField(default=0)),
                ('temp_data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_flow_forge.flowbatch')),
            ],
        ),
    ]
