# Generated by Django 5.0 on 2024-04-14 16:38

import django.core.serializers.json
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0012_rename_total_batches_batchhandler_total_batch_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchtempdata',
            name='batch_handler',
        ),
        migrations.CreateModel(
            name='FlowBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_batch_number', models.IntegerField(default=0)),
                ('temp_data', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
                ('batch_handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='django_flow_forge.batchhandler')),
            ],
        ),
        migrations.AddField(
            model_name='batchtempdata',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batch_temp_data', to='django_flow_forge.flowbatch'),
        ),
    ]
