# Generated by Django 5.0 on 2024-04-14 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0013_remove_batchtempdata_batch_handler_flowbatch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BatchTempData',
        ),
    ]
