# Generated by Django 5.0 on 2024-04-17 20:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0014_delete_batchtempdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchhandler',
            name='date_initialised',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2024, 4, 17, 20, 8, 36, 615438, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
