# Generated by Django 5.0.7 on 2024-08-20 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0017_alter_executedflow_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_data', models.BinaryField(blank=True, null=True)),
                ('ml_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ml_model', to='django_flow_forge.mlresult')),
            ],
        ),
    ]
