# Generated by Django 5.0.7 on 2024-08-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0020_remove_mlresult_feature_importances'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mlresult',
            name='notes',
        ),
        migrations.AddField(
            model_name='mlresult',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
