# Generated by Django 5.0.2 on 2024-08-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0021_remove_mlresult_notes_mlresult_metadata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExecutedFlow',
            new_name='ExecutedPipeline',
        ),
        migrations.RenameModel(
            old_name='Flow',
            new_name='Pipeline',
        ),
        migrations.RenameModel(
            old_name='FlowBatch',
            new_name='PipelineBatch',
        ),
        migrations.RenameModel(
            old_name='FlowTask',
            new_name='PipelineTask',
        ),
    ]
