# Generated by Django 5.0.2 on 2024-08-22 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0022_rename_executedflow_executedpipeline_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipeline',
            options={'permissions': [('django_pipeline_admin_access', 'Can access Django Flow Admin')]},
        ),
        migrations.RenameField(
            model_name='executedpipeline',
            old_name='flow_complete',
            new_name='pipeline_complete',
        ),
        migrations.RenameField(
            model_name='executedpipeline',
            old_name='flow_id_snapshot',
            new_name='pipeline_id_snapshot',
        ),
        migrations.RenameField(
            model_name='executedpipeline',
            old_name='flow_name_snapshot',
            new_name='pipeline_name_snapshot',
        ),
        migrations.RenameField(
            model_name='executedpipeline',
            old_name='flow_snapshot',
            new_name='pipeline_snapshot',
        ),
        migrations.RenameField(
            model_name='executedtask',
            old_name='flow_run',
            new_name='pipeline_run',
        ),
        migrations.RenameField(
            model_name='mlresult',
            old_name='executed_flow',
            new_name='executed_pipeline',
        ),
        migrations.RenameField(
            model_name='pipeline',
            old_name='flow_display_name',
            new_name='pipeline_display_name',
        ),
        migrations.RenameField(
            model_name='pipeline',
            old_name='flow_name',
            new_name='pipeline_name',
        ),
        migrations.RenameField(
            model_name='pipelinebatch',
            old_name='flow_batch_number',
            new_name='pipeline_batch_number',
        ),
        migrations.RenameField(
            model_name='pipelinetask',
            old_name='flow',
            new_name='pipeline',
        ),
        migrations.RemoveField(
            model_name='executedpipeline',
            name='flow',
        ),
        migrations.RemoveField(
            model_name='executedpipeline',
            name='flow_batch',
        ),
        migrations.AddField(
            model_name='executedpipeline',
            name='pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_runs', to='django_flow_forge.pipeline'),
        ),
        migrations.AddField(
            model_name='executedpipeline',
            name='pipeline_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executed_pipelines', to='django_flow_forge.pipelinebatch'),
        ),
        migrations.AlterField(
            model_name='executedpipeline',
            name='batch_handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executed_pipelines', to='django_flow_forge.batchhandler'),
        ),
        migrations.AlterUniqueTogether(
            name='pipelinetask',
            unique_together={('pipeline', 'task_name')},
        ),
    ]
