# Generated by Django 5.0.2 on 2024-02-24 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mlops', '0023_mlresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlresult',
            name='executed_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ml_runs', to='django_mlops.executedprocess'),
        ),
    ]
