# Generated by Django 5.0.2 on 2024-08-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0023_alter_pipeline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinetask',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
