# Generated by Django 5.0.2 on 2024-08-22 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0024_pipelinetask_verbose_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipelinetask',
            name='depends_bidirectionally_with',
        ),
    ]
