# Generated by Django 5.1 on 2024-08-30 20:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0025_remove_pipelinetask_depends_bidirectionally_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='executedtask',
            name='last_checkpoint_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='executedtask',
            name='last_checkpoint_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
