# Generated by Django 5.1 on 2024-11-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_flow_forge', '0027_alter_executedpipeline_last_checkpoint_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executedtask',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
