name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Or your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false  # This is necessary for JamesIves/github-pages-deploy-action

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify your Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs  # Install MkDocs
        pip install mkdocs-material  # Optional: Install the Material theme or any other plugins/themes you use
        # Install any other dependencies you might have
        # pip install -r requirements.txt  # Uncomment if you have additional requirements

    - name: Build MkDocs site
      run: mkdocs build --verbose --clean

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site  # Default MkDocs build output directory
        keep_files: false  # Set to true if you want to keep files already in the gh-pages branch
