name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main  # Or your default branch if different
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV # (3)!
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material # (4)!
      - run: mkdocs gh-deploy --force

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs  # Install MkDocs
        pip install mkdocs-material  # Optional: Install the Material theme or any other plugins/themes you use
        # Install any other dependencies you might have
        # pip install -r requirements.txt  # Uncomment if you have additional requirements

    - name: Build MkDocs site
      run: mkdocs build --verbose --clean

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site  # Default MkDocs build output directory
        keep_files: false  # Set to true if you want to keep files already in the gh-pages branch
