name: Publish Python 🐍 distribution 📦 to PyPI

on:
  push:
    branches:
      - main 

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Set up the Python version to match your project environment

    - name: Install flit
      run: python -m pip install flit

    - name: Build and publish to PyPI
      env:
        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}  # Set PYPI_TOKEN in your repository secrets
      run: |
        flit publish --token $PYPI_TOKEN

